<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ItemRecognition.Domain\ItemRecognition.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Common\" />
      <Folder Include="Ports\" />
      <Folder Include="Prompts\" />
      <Folder Include="UseCases\" />
    </ItemGroup>

</Project>
